[project]
name = "sentinel-ebpf"
version = "0.1.0"
description = "Falco-like eBPF agent and detector"
requires-python = ">=3.11"
dependencies = [
  "bcc==0.1.10",
  "grpcio==1.76.0",
  "grpcio-tools==1.76.0",
  "PyYAML==6.0.2",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["agent", "detector"]
