{{- if .Values.agent.storage.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sentinel-ebpf.fullname" . }}-logs
  labels:
    {{- include "sentinel-ebpf.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.agent.storage.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.agent.storage.pvc.size }}
  {{- if .Values.agent.storage.pvc.storageClassName }}
  storageClassName: {{ .Values.agent.storage.pvc.storageClassName }}
  {{- end }}
{{- end }}
