{{- if and .Values.probe.rbac.create .Values.probe.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sentinel-ebpf.fullname" . }}
  labels:
    {{- include "sentinel-ebpf.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sentinel-ebpf.fullname" . }}
  labels:
    {{- include "sentinel-ebpf.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sentinel-ebpf.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "sentinel-ebpf.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
