{{- if .Values.agent.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinel-ebpf.serviceAccountName" . }}
  labels:
    {{- include "sentinel-ebpf.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.agent.serviceAccount.annotations | nindent 4 }}
imagePullSecrets:
  {{- toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
