{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-ebpf.fullname" . }}-ui
  labels:
    {{- include "sentinel-ebpf.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    {{- include "sentinel-ebpf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: http
{{- end }}
